import ProfilePage from "@/components/profile";

export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

const Profile = () => {
  return <ProfilePage />;
};

export default Profile;
